import type { Coordinates, Reward, Spot } from './types'

export const DEMO_ORIGIN: Coordinates = [-77.033, -12.1195]
export const AREQUIPA_ORIGIN: Coordinates = [-71.537, -16.399]
export const AREQUIPA_TEST_POINTS: Array<{ name: string; coordinates: Coordinates; severity: 'high' | 'medium' | 'clean' }> = [
  { name: 'Plaza de Armas', coordinates: [-71.5369, -16.3988], severity: 'high' },
  { name: 'Vallecito', coordinates: [-71.5511, -16.4074], severity: 'medium' },
  { name: 'Parque Selva Alegre', coordinates: [-71.5221, -16.3859], severity: 'clean' },
]
export const spots: Spot[] = [
  { id: 'LM-MIR-0101', name: 'Parque Kennedy', district: 'Miraflores', zone: 'Parques', coordinates: [-77.0304, -12.1211], severity: 'medium', points: 40, minutes: 15, image: 'https://images.unsplash.com/photo-1587974928442-77dc3e0dba72?w=600&auto=format&fit=crop', description: 'Ayudemos a recuperar el entorno del parque. Recoge botellas, envolturas y residuos ligeros de las áreas peatonales. Separa los materiales reciclables.', validator: 'Lucía · Embajadora ambiental', updated: 'Hace 25 min' },
  { id: 'LM-MIR-0102', name: 'Playa Makaha', district: 'Miraflores', zone: 'Playas', coordinates: [-77.0379, -12.1274], severity: 'high', points: 80, minutes: 30, image: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=600&auto=format&fit=crop', description: 'Una playa más limpia empieza con pequeños pasos. Retira plásticos y residuos de la zona seca. Permanece lejos del oleaje y de los acantilados.', validator: 'Diego · Embajador ambiental', updated: 'Hace 40 min' },
  { id: 'LM-MIR-0103', name: 'Malecón de la Reserva', district: 'Miraflores', zone: 'Parques', coordinates: [-77.0319, -12.1302], severity: 'medium', points: 50, minutes: 20, image: 'https://images.unsplash.com/photo-1580837119756-563d608dd119?w=600&auto=format&fit=crop', description: 'Devuelve el verde al malecón recogiendo residuos de los senderos públicos. Usa guantes y deposita las bolsas en el punto de acopio.', validator: 'Lucía · Embajadora ambiental', updated: 'Hace 1 h' },
  { id: 'LM-MIR-0104', name: 'Parque del Amor', district: 'Miraflores', zone: 'Parques', coordinates: [-77.0368, -12.1225], severity: 'clean', points: 30, minutes: 15, image: 'https://images.unsplash.com/photo-1601923695251-0a59950c5112?w=600&auto=format&fit=crop', description: 'Esta zona ya fue recuperada por la comunidad. Explora otras misiones o reporta nuevos residuos si el lugar vuelve a necesitar ayuda.', validator: 'María · Embajadora ambiental', updated: 'Hace 2 h' },
  { id: 'LM-MIR-0105', name: 'Óvalo de Miraflores', district: 'Miraflores', zone: 'Calles', coordinates: [-77.0291, -12.1175], severity: 'high', points: 60, minutes: 25, image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&auto=format&fit=crop', description: 'Recoge residuos ligeros en las veredas del óvalo. Respeta los cruces peatonales y no ingreses a la calzada.', validator: 'Diego · Embajador ambiental', updated: 'Hace 50 min' },
  { id: 'LM-MIR-0106', name: 'Parque María Reiche', district: 'Miraflores', zone: 'Parques', coordinates: [-77.0486, -12.1135], severity: 'medium', points: 45, minutes: 20, image: 'https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=600&auto=format&fit=crop', description: 'Recupera los senderos del parque y clasifica los residuos reciclables. Una misión ideal para tu paseo por el malecón.', validator: 'María · Embajadora ambiental', updated: 'Hace 1 h' },
  { id: 'LM-BAR-0201', name: 'Playa Los Yuyos', district: 'Barranco', zone: 'Playas', coordinates: [-77.0221, -12.1531], severity: 'high', points: 90, minutes: 35, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop', description: 'Limpieza de residuos ligeros en la playa. No manipules vidrios, agujas ni residuos peligrosos. Reporta esos materiales al validador.', validator: 'Diego · Embajador ambiental', updated: 'Hace 30 min' },
  { id: 'LM-BAR-0202', name: 'Parque Municipal de Barranco', district: 'Barranco', zone: 'Parques', coordinates: [-77.0202, -12.1494], severity: 'medium', points: 40, minutes: 15, image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&auto=format&fit=crop', description: 'Un pequeño cambio para nuestro barrio. Recoge envolturas y botellas alrededor de las bancas y jardines.', validator: 'Lucía · Embajadora ambiental', updated: 'Hace 2 h' },
  { id: 'LM-RIM-0412', name: 'Río Rímac · Puente del Ejército', district: 'Rímac', zone: 'Ríos', coordinates: [-77.0468, -12.0384], severity: 'high', points: 100, minutes: 40, image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=600&auto=format&fit=crop', description: 'Intervención únicamente en la zona peatonal habilitada. No bajes a la ribera ni entres al agua. Coordina con el embajador antes de comenzar.', validator: 'Carlos · Embajador ambiental', updated: 'Hace 2 h' },
  { id: 'LM-RIM-0413', name: 'Alameda de los Descalzos', district: 'Rímac', zone: 'Parques', coordinates: [-77.0268, -12.0345], severity: 'medium', points: 50, minutes: 20, image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&auto=format&fit=crop', description: 'Ayuda a mantener limpia la alameda. Solo residuos ligeros y no peligrosos en espacios de acceso público.', validator: 'Carlos · Embajador ambiental', updated: 'Hace 1 h' },
  { id: 'LM-SIS-0301', name: 'Bosque El Olivar', district: 'San Isidro', zone: 'Parques', coordinates: [-77.0341, -12.0972], severity: 'clean', points: 40, minutes: 20, image: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=600&auto=format&fit=crop', description: 'La comunidad ha recuperado este espacio. Cuidemos juntos sus árboles y senderos.', validator: 'María · Embajadora ambiental', updated: 'Hace 3 h' },
  { id: 'LM-SIS-0302', name: 'Parque Alfonso Ugarte', district: 'San Isidro', zone: 'Parques', coordinates: [-77.0458, -12.0955], severity: 'medium', points: 35, minutes: 15, image: 'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?w=600&auto=format&fit=crop', description: 'Recoge envolturas y botellas de las áreas de tránsito del parque, sin intervenir los jardines.', validator: 'María · Embajadora ambiental', updated: 'Hace 45 min' },
]
export const rewards: Reward[] = [
  { id: 'rice', title: 'Arroz para tu hogar', description: 'Una bolsa de arroz de 1 kg. Un pequeño aporte a tu mesa por un gran aporte a tu ciudad.', cost: 250, stock: 24, category: 'Alimentos', icon: 'Wheat', color: '#f4ecd7', sponsor: 'Bodega Verde · demo', location: 'Punto de entrega demo · Miraflores', image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&auto=format&fit=crop' },
  { id: 'oil', title: 'Aceite vegetal', description: 'Botella de aceite vegetal de 1 litro para compartir en casa.', cost: 300, stock: 18, category: 'Alimentos', icon: 'Droplets', color: '#f7edc8', sponsor: 'Bodega Verde · demo', location: 'Punto de entrega demo · Miraflores', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop' },
  { id: 'kit', title: 'Un nuevo comienzo', description: 'Kit de útiles: cuaderno, lápices y borrador para tus próximas ideas.', cost: 180, stock: 30, category: 'Accesorios', icon: 'NotebookPen', color: '#e5e7f7', sponsor: 'Campus Circular · demo', location: 'Punto de entrega demo · San Isidro', image: 'https://images.unsplash.com/photo-1581465829681-e4b7a61ae43f?w=600&auto=format&fit=crop' },
  { id: 'coffee', title: 'Tu pausa favorita', description: 'Un café americano y un momento para celebrar lo que hiciste por Lima.', cost: 120, stock: 40, category: 'Experiencias', icon: 'Coffee', color: '#ebdfd2', sponsor: 'Café de Barrio · demo', location: 'Punto de entrega demo · Barranco', image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop' },
  { id: 'bottle', title: 'Menos plástico, más vida', description: 'Botella reutilizable de 500 ml para acompañarte en cada misión.', cost: 400, stock: 12, category: 'Accesorios', icon: 'BottleWine', color: '#dceee7', sponsor: 'Reusa Perú · demo', location: 'Punto de entrega demo · Miraflores', image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop' },
  { id: 'plant', title: 'Llévate un poco de verde', description: 'Una pequeña planta de vivero para seguir cultivando el cambio.', cost: 200, stock: 16, category: 'Experiencias', icon: 'Sprout', color: '#e7efd5', sponsor: 'Raíces · demo', location: 'Punto de entrega demo · Miraflores', image: 'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=600&auto=format&fit=crop' },
]
export const districts = ['Miraflores', 'Barranco', 'San Isidro', 'Rímac', 'Lima Cercado']
export const severityLabels = { high: 'Prioridad alta', medium: 'Prioridad media', clean: 'Zona recuperada' }
export const formatDate = (value: string) => new Intl.DateTimeFormat('es-PE', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value))
export function distance(a: Coordinates, b: Coordinates) {
  const rad = Math.PI / 180
  const p = Math.sin((b[1] - a[1]) * rad / 2) ** 2 + Math.cos(a[1] * rad) * Math.cos(b[1] * rad) * Math.sin((b[0] - a[0]) * rad / 2) ** 2
  return 6371000 * 2 * Math.atan2(Math.sqrt(p), Math.sqrt(1 - p))
}
export const formatDistance = (meters: number) => meters < 1000 ? `${Math.round(meters / 10) * 10} m` : `${(meters / 1000).toFixed(1)} km`
