import { useMemo, useState } from 'react'
import { ArrowRight, ArrowUpRight, Clock3, Compass, Flag, Leaf, ListFilter, MapPin, Search, Sparkles, Trees, Waves, X } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import MapView from './MapView'
import { useEco } from './store'
import { Badge, Empty, Points, Progress } from './ui'
import { AREQUIPA_ORIGIN, DEMO_ORIGIN, distance, formatDistance } from './data'
import type { Coordinates, Spot } from './types'

export default function Explore() {
  const { spots, profile, missions, joined } = useEco()
  const [searchParams] = useSearchParams()
  const arequipaPreview = searchParams.get('city')?.toLowerCase() === 'arequipa'
  const [query, setQuery] = useState(''), [zone, setZone] = useState('Todos'), [radius, setRadius] = useState(0)
  const [selected, setSelected] = useState<Spot | undefined>(), [filters, setFilters] = useState(false)
  const [position, setPosition] = useState<Coordinates>(arequipaPreview ? AREQUIPA_ORIGIN : DEMO_ORIGIN), [source, setSource] = useState<'demo' | 'gps'>('demo')
  const visible = useMemo(() => arequipaPreview ? [] : spots.filter(s => !s.hidden && (zone === 'Todos' || s.zone === zone) && (!radius || distance(position, s.coordinates) <= radius) && `${s.name} ${s.district}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a, b) => distance(position, a.coordinates) - distance(position, b.coordinates)), [arequipaPreview, spots, query, zone, radius, position])
  const nearby = visible.filter(s => s.severity !== 'clean')
  const completed = missions.filter(m => m.status === 'approved').length
  const active = missions.find(m => m.status === 'active')
  return <div className="explore-page">
    <div className="explore-heading"><div><p className="eyebrow">UN PEQUEÑO PASO. UN GRAN CAMBIO.</p><h1>{arequipaPreview ? 'Arequipa.' : 'Tu ciudad.'} <span>Tu próxima misión.</span></h1><p>Hola, {profile.name}. Hoy es un buen día para dejar huella verde.</p></div><Link className="button secondary report-desktop" to="/reportar"><MapPin size={17} /> Reportar un foco <span>+</span></Link></div>
    <div className="explore-summary"><div className="summary-item"><span className="stat-icon mint"><Flag size={19} /></span><div><strong>{spots.filter(s => s.severity !== 'clean' && !s.hidden).length}</strong><span>misiones por descubrir</span></div></div><div className="summary-item"><span className="stat-icon green"><Trees size={20} /></span><div><strong>{spots.filter(s => s.severity === 'clean').length}</strong><span>zonas recuperadas</span></div></div><div className="summary-item"><span className="stat-icon gold"><Sparkles size={19} /></span><div><strong>{spots.filter(s => s.severity !== 'clean' && !s.hidden).reduce((sum, s) => sum + s.points, 0)} <small>ECO</small></strong><span>esperando por tu impacto</span></div></div><div className="summary-note"><span className="live-dot" /> Explora. Limpia. Transforma.<small>Escenario de demostración</small></div></div>
    <div className="explore-grid"><section className="map-section" aria-label="Explorar misiones">
      <div className="map-toolbar"><div className="search-field"><Search size={18} /><input aria-label="Buscar lugar o distrito" placeholder="Busca un lugar o distrito" value={query} onChange={e => { setQuery(e.target.value); setSelected(undefined) }} />{query && <button aria-label="Limpiar búsqueda" onClick={() => setQuery('')}><X size={16} /></button>}</div><button className={`filter-button ${radius ? 'selected' : ''}`} onClick={() => setFilters(!filters)} aria-expanded={filters}><ListFilter size={18} /><span>Filtros</span>{radius > 0 && <i />}</button></div>
      {filters && <div className="distance-filter"><label htmlFor="distance">Distancia desde {source === 'demo' ? 'posición demo' : 'tu ubicación'}</label><select id="distance" value={radius} onChange={e => { setRadius(Number(e.target.value)); setSelected(undefined) }}><option value={0}>{arequipaPreview ? 'Toda Arequipa' : 'Toda Lima'}</option><option value={500}>Hasta 500 m</option><option value={1000}>Hasta 1 km</option><option value={3000}>Hasta 3 km</option><option value={10000}>Hasta 10 km</option></select></div>}
      <div className="map-frame"><MapView spots={visible} selected={selected} onSelect={setSelected} position={position} onPosition={(coords, mode) => { setPosition(coords); setSource(mode) }} /><div className="map-zone-tabs">{[{ name: 'Todos', icon: Compass }, { name: 'Parques', icon: Trees }, { name: 'Playas', icon: Waves }, { name: 'Ríos', icon: Waves }, { name: 'Calles', icon: MapPin }].map(({ name, icon: Icon }) => <button key={name} className={zone === name ? 'active' : ''} onClick={() => { setZone(name); setSelected(undefined) }} aria-pressed={zone === name}><Icon size={15} />{name}</button>)}</div>
      {selected && <div className="map-spot-preview"><img src={selected.image} alt="Imagen ilustrativa del entorno" /><div><Badge severity={selected.severity} /><h3>{selected.name}</h3><span><MapPin size={12} /> {formatDistance(distance(position, selected.coordinates))} <span>·</span> <Points value={selected.points} small /></span><Link to={`/foco/${selected.id}`}>Ver misión <ArrowRight size={15} /></Link></div><button className="icon-button" aria-label="Cerrar foco" onClick={() => setSelected(undefined)}><X size={17} /></button></div>}
      </div><div className="map-caption"><span><MapPin size={12} /> {source === 'demo' ? `Ubicación de demostración · ${arequipaPreview ? 'Arequipa' : 'Miraflores'}` : 'Ubicación del dispositivo'}</span><span>{arequipaPreview ? '3 puntos de prueba' : `${visible.length} focos en el mapa`}</span></div>
    </section><aside className="nearby-panel">
      <div className="nearby-heading"><div><span className="eyebrow">CADA MINUTO CUENTA</span><h2>{arequipaPreview ? 'Puntos de prueba' : 'Cerca de ti'} <span>{arequipaPreview ? 3 : nearby.length}</span></h2></div><Compass size={22} /></div><p className="muted nearby-intro">Unos minutos de tu día pueden cambiar un lugar.</p>
      <div className="nearby-list">{nearby.slice(0, 3).map((spot, index) => <button key={spot.id} className={`nearby-card ${selected?.id === spot.id ? 'selected' : ''}`} onClick={() => setSelected(spot)}><div className="nearby-photo"><img src={spot.image} alt="Entorno ilustrativo de la misión" /><Badge severity={spot.severity} />{index === 0 && <span className="recommended">PARA TI</span>}</div><div className="nearby-card-content"><span className="spot-district">{spot.district} <span>·</span> {spot.zone}</span><h3>{spot.name}<ArrowUpRight size={17} /></h3><div className="nearby-card-bottom"><span><MapPin size={13} />{formatDistance(distance(position, spot.coordinates))}<i>·</i><Clock3 size={13} />{spot.minutes} min</span><Points value={spot.points} small /></div></div></button>)}</div>
      {nearby.length === 0 && <Empty title="Un respiro para esta zona" text="Prueba otro distrito, tipo de zona o amplía la distancia." />}
      <Link className="all-missions-link" to="/misiones?tab=descubrir">Ver todas las misiones <ArrowRight size={17} /></Link>
    </aside></div>
    <div className="explore-bottom"><section className="weekly-challenge"><div className="challenge-art"><Leaf size={34} /><span>+</span></div><div className="challenge-copy"><span className="eyebrow">TU RETO SEMANAL</span><h3>Tres misiones. Una Lima más limpia.</h3><p>Completa 3 limpiezas y desbloquea la insignia «Agente del cambio».</p></div><div className="challenge-progress"><div><b>{Math.min(completed, 3)} de 3</b><span>misiones</span></div><Progress value={completed / 3 * 100} label="Reto de tres misiones" /><Link to="/perfil">Ver mi progreso <ArrowRight size={14} /></Link></div></section><section className="impact-invite"><div><span className="eyebrow">EL CAMBIO EMPIEZA CONTIGO</span><h3>{active ? 'Tu misión sigue en marcha.' : joined ? 'Tu siguiente logro está cerca.' : 'Bienvenido al lado verde.'}</h3></div><Link to={active ? `/mision/${active.id}` : joined ? '/perfil' : '/bienvenida'} aria-label={active ? 'Continuar misión' : 'Comenzar mi aventura'}><ArrowUpRight size={24} /></Link></section></div>
  </div>
}
