import { useState } from 'react'
import { ArrowRight, Camera, Check, CheckCircle2, ChevronRight, Clock3, Leaf, MapPin, Minus, Navigation, Plus, ShieldCheck, Trash2, TriangleAlert, Upload } from 'lucide-react'
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { useEco } from './store'
import { Badge, DemoNote, Empty, Modal, PageTitle, Points, useToast } from './ui'
import { DEMO_ORIGIN, distance, formatDate, formatDistance } from './data'
import { demoEvidence, readEvidence } from './evidence'
import type { Coordinates, Evidence, Mission } from './types'

const statusNames = { active: 'En curso', pending: 'En revisión', approved: 'Completada', rejected: 'Necesita cambios' }
export function SpotDetail() {
  const { id } = useParams(), { spots, startMission, missions } = useEco(), navigate = useNavigate(), toast = useToast()
  const spot = spots.find(s => s.id === id), [safety, setSafety] = useState(false)
  if (!spot) return <Empty title="Este foco no está disponible" text="Regresa al mapa para encontrar una misión cercana." to="/" />
  const begin = () => { try { const missionId = startMission(spot.id); void navigate(`/mision/${missionId}`) } catch (error) { toast((error as Error).message) } }
  const previous = missions.filter(m => m.spotId === spot.id && m.status === 'approved')
  return <div className="standard-page"><PageTitle back eyebrow="DESCUBRE TU PRÓXIMO IMPACTO" title={spot.name} description={`${spot.district}, Lima · ${spot.zone}`} /><div className="detail-grid"><section><div className="detail-photo"><img src={spot.image} alt="Fotografía ilustrativa del entorno de la misión" /><Badge severity={spot.severity} /><span className="photo-caption">Imagen ilustrativa · escenario demo</span></div><div className="surface detail-description"><span className="mono">{spot.id}</span><h2>Un lugar que podemos transformar</h2><p>{spot.description}</p><div className="detail-metrics"><div><MapPin /><b>{formatDistance(distance(DEMO_ORIGIN, spot.coordinates))}</b><small>Desde posición demo</small></div><div><Clock3 /><b>{spot.minutes} minutos</b><small>Tiempo estimado</small></div><div><Trash2 /><b>Residuos ligeros</b><small>Recolección manual</small></div></div><h3>Antes de salir</h3><ul className="check-list"><li><Check size={17} /> Lleva guantes, bolsas y agua.</li><li><Check size={17} /> Usa zapatos cerrados y cuida tu entorno.</li><li><Check size={17} /> No manipules agujas, químicos ni residuos peligrosos.</li><li><Check size={17} /> Deposita las bolsas en un punto de acopio autorizado.</li></ul><h3>Historial de este foco</h3><p className="muted">{previous.length ? `${previous.length} limpieza(s) aprobada(s) durante esta demostración.` : 'Aún no hay intervenciones registradas en tu demo.'}</p></div></section><aside><section className="surface mission-reward"><span className="eyebrow">TU ACCIÓN TIENE VALOR</span><div className="large-reward"><Leaf size={27} /><strong>+{spot.points}</strong><span>ECO</span></div><p>Puntos por una misión aprobada.<br />Canjéalos por algo bueno para ti.</p><hr /><div className="validator-line"><span className="avatar teal">{spot.validator.slice(0, 1)}</span><div><small>Te acompaña</small><b>{spot.validator}</b></div><ShieldCheck size={19} /></div><p className="muted small-text">Última actualización: {spot.updated} · demo</p>{spot.severity !== 'clean' && !spot.hidden ? <><label className="checkbox-row"><input type="checkbox" checked={safety} onChange={e => setSafety(e.target.checked)} /> Leí las indicaciones y llevaré materiales de protección.</label><button className="button primary full" disabled={!safety} onClick={begin}>Iniciar misión <ArrowRight size={18} /></button></> : <div className="success-inline"><CheckCircle2 />{spot.hidden ? 'Foco pausado por administración' : '¡La comunidad recuperó esta zona!'}</div>}<Link className="button text-button full" to="/">Seguir explorando</Link></section><DemoNote>Las misiones y sus fotos son ilustrativas. No son reportes oficiales de contaminación.</DemoNote></aside></div></div>
}

export function Missions() {
  const { missions, spots } = useEco(), [params] = useSearchParams(), [tab, setTab] = useState<'activas' | 'historial' | 'descubrir'>(params.get('tab') === 'descubrir' ? 'descubrir' : 'activas')
  const filtered = missions.filter(m => tab === 'historial' ? m.status === 'approved' || m.status === 'rejected' : m.status === 'active' || m.status === 'pending')
  const tabs = [['activas', 'En curso'], ['historial', 'Mi historial'], ['descubrir', 'Descubrir']] as const
  return <div className="standard-page"><PageTitle eyebrow="MINUTOS QUE HACEN LA DIFERENCIA" title="Mis misiones" description="Cada limpieza es una historia de cambio. Esta es la tuya." action={<Link className="button primary" to="/">Explorar mapa <ArrowRight size={17} /></Link>} /><div className="tabs">{tabs.map(([value, label]) => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{label}</button>)}</div>{tab === 'descubrir' ? <div className="mission-grid">{spots.filter(s => !s.hidden && s.severity !== 'clean').map(s => <Link className="surface discover-card" key={s.id} to={`/foco/${s.id}`}><img src={s.image} alt="Entorno ilustrativo" /><div><Badge severity={s.severity} /><h3>{s.name}</h3><p className="muted">{s.district} · {s.minutes} min</p><div className="row-between"><Points value={s.points} /><ArrowRight size={19} /></div></div></Link>)}</div> : filtered.length ? <div className="mission-list">{filtered.map(m => { const spot = spots.find(s => s.id === m.spotId); return <Link className="surface mission-row" key={m.id} to={`/mision/${m.id}`}><img src={spot?.image} alt="Entorno ilustrativo" /><div><span className={`status-label ${m.status}`}>{statusNames[m.status]}</span><h3>{spot?.name}</h3><p>{formatDate(m.startedAt)} · {spot?.district}</p></div><Points value={m.points} /><ChevronRight size={20} /></Link> })}</div> : <Empty title={tab === 'historial' ? 'Tu impacto empieza con una misión' : 'Tu próxima aventura está cerca'} text={tab === 'historial' ? 'Aquí aparecerán tus misiones revisadas y las historias que has ayudado a cambiar.' : 'Descubre un foco, lleva tus materiales y transforma unos minutos en una ciudad más limpia.'} to="/" />}</div>
}

export function MissionPage() {
  const { id } = useParams(), state = useEco(), toast = useToast(), navigate = useNavigate()
  const mission = state.missions.find(m => m.id === id), spot = state.spots.find(s => s.id === mission?.spotId)
  const [busy, setBusy] = useState(''), [cancel, setCancel] = useState(false), [demo, setDemo] = useState(true)
  const [gps, setGps] = useState<{ coordinates: Coordinates; accuracy: number; time: number } | null>(null)
  if (!mission || !spot) return <Empty title="No encontramos esta misión" text="Puedes comenzar una nueva aventura en el mapa." to="/" />
  const verifyGPS = () => { setBusy('gps'); navigator.geolocation?.getCurrentPosition(p => { setGps({ coordinates: [p.coords.longitude, p.coords.latitude], accuracy: p.coords.accuracy, time: Date.now() }); setBusy('') }, e => { toast(e.code === 1 ? 'Permite la ubicación en tu navegador para verificar tu llegada.' : 'No pudimos obtener una posición precisa. Inténtalo de nuevo.'); setBusy('') }, { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }); if (!navigator.geolocation) { setBusy(''); toast('Este navegador no admite GPS.') } }
  const gpsValid = demo || !!(gps && distance(gps.coordinates, spot.coordinates) <= 50 && gps.accuracy <= 50 && Date.now() - gps.time < 120000)
  const upload = async (kind: 'before' | 'after', file?: File) => {
    if (!gpsValid) { toast('Verifica tu ubicación a menos de 50 m del foco, con precisión de 50 m o mejor.'); return }
    setBusy(kind)
    try { const evidence = file ? await readEvidence(file, demo ? spot.coordinates : gps!.coordinates, demo ? 10 : gps!.accuracy, demo) : await demoEvidence(kind, spot.coordinates); state.updateEvidence(mission.id, kind, evidence); toast('Evidencia guardada en este dispositivo.') }
    catch (error) { toast((error as Error).message) } finally { setBusy('') }
  }
  const submit = () => { try { state.submitMission(mission.id); toast('¡Evidencia enviada a la cola de revisión demo!') } catch (error) { toast((error as Error).message) } }
  return <div className="standard-page"><PageTitle back eyebrow={mission.status === 'active' ? 'PASO A PASO, CAMBIAMOS LIMA' : 'TU IMPACTO TIENE HISTORIA'} title={mission.status === 'active' ? 'Tu misión está en marcha' : statusNames[mission.status]} description={spot.name} /><div className="detail-grid"><section>
    {mission.status !== 'active' && <MissionStatus mission={mission} />}
    <div className="surface evidence-panel"><div className="row-between"><h2>Evidencia de tu impacto</h2><span className="mono">{spot.id}</span></div><div className="step-line"><span className={mission.before ? 'done' : 'current'}><i>{mission.before ? <Check size={13} /> : '1'}</i> Antes</span><b /><span className={mission.after ? 'done' : mission.before ? 'current' : ''}><i>{mission.after ? <Check size={13} /> : '2'}</i> Después</span><b /><span className={mission.status !== 'active' ? 'done' : ''}><i>3</i> Validación</span></div><div className="evidence-grid">{(['before', 'after'] as const).map(kind => <EvidenceCard key={kind} kind={kind} evidence={mission[kind]} active={mission.status === 'active'} disabled={!!busy || (kind === 'after' && !mission.before)} busy={busy === kind} demo={demo} onFile={file => void upload(kind, file)} onDemo={() => void upload(kind)} />)}</div><p className="muted small-text">Encuadra el mismo lugar antes y después. No incluyas rostros ni información personal. JPG, PNG o WebP, hasta 12 MB.</p>{mission.status === 'active' && <><div className="bags-row"><div><h3>Bolsas recolectadas</h3><p className="muted">Cuenta las bolsas que llevaste al punto de acopio.</p></div><div className="stepper"><button aria-label="Quitar una bolsa" disabled={mission.bags <= 1} onClick={() => state.setBags(mission.id, mission.bags - 1)}><Minus size={17} /></button><strong>{mission.bags}</strong><button aria-label="Agregar una bolsa" disabled={mission.bags >= 50} onClick={() => state.setBags(mission.id, mission.bags + 1)}><Plus size={17} /></button></div></div><button className="button primary full" disabled={!mission.before || !mission.after || !!busy} onClick={submit}>Enviar a validación <ShieldCheck size={18} /></button></>}</div>
    {mission.status === 'approved' && <Link className="certificate-link" to={`/certificado/${mission.id}`}><div className="stat-icon mint"><ShieldCheck /></div><div><b>Tu certificado de impacto</b><p>Consulta las evidencias y descarga tu registro demo.</p></div><ArrowRight size={20} /></Link>}
    </section><aside><section className="surface"><span className="eyebrow">MISIÓN DE LIMPIEZA</span><h2>{spot.name}</h2><p className="muted">{spot.district} · {spot.zone}</p><div className="mission-meta"><span>Recompensa</span><Points value={mission.points} /></div><div className="mission-meta"><span>Estado</span><span className={`status-label ${mission.status}`}>{statusNames[mission.status]}</span></div>{mission.status === 'active' && <><hr /><label className="switch-row"><span><b>Recorrido de demostración</b><small>Prueba la misión desde cualquier lugar.</small></span><input type="checkbox" role="switch" checked={demo} onChange={e => { setDemo(e.target.checked); setGps(null) }} /></label><div className={`gps-status ${gpsValid ? '' : 'warning'}`}><Navigation size={20} /><div><b>{demo ? 'GPS simulado · 10 m' : gps ? `${formatDistance(distance(gps.coordinates, spot.coordinates))} del foco` : 'Verifica tu llegada'}</b><small>{demo ? 'Coordenadas de ejemplo, no verificadas' : gps ? `Precisión ±${Math.round(gps.accuracy)} m` : 'Necesitas estar a menos de 50 metros.'}</small></div></div>{!demo && <button className="button secondary full" onClick={verifyGPS} disabled={busy === 'gps'}>{busy === 'gps' ? 'Obteniendo ubicación…' : 'Verificar ubicación GPS'}</button>}<button className="button text-button danger full" onClick={() => setCancel(true)}>Cancelar misión</button></>}{mission.status === 'pending' && <Link className="button secondary full" to="/validador">Probar rol de validador <ArrowRight size={16} /></Link>}{mission.status === 'rejected' && <button className="button primary full" onClick={() => { try { state.retryMission(mission.id) } catch (e) { toast((e as Error).message) } }}>Corregir evidencia <Camera size={17} /></button>}{mission.status === 'approved' && <Link className="button primary full" to="/recompensas">Disfrutar mis recompensas <ArrowRight size={17} /></Link>}</section><DemoNote>Las fotos se guardan localmente. El SHA-256 se calcula sobre el archivo original; la hora proviene de este dispositivo. No hay verificación de IA ni registro on-chain.</DemoNote></aside></div>{cancel && <Modal title="¿Cancelar esta misión?" onClose={() => setCancel(false)}><p>Se eliminará el borrador de esta misión. No perderás puntos y podrás volver a empezar.</p><div className="modal-actions"><button className="button secondary" onClick={() => setCancel(false)}>Continuar misión</button><button className="button danger-fill" onClick={() => { state.cancelMission(mission.id); void navigate('/misiones') }}>Sí, cancelar</button></div></Modal>}</div>
}

function EvidenceCard({ kind, evidence, active, disabled, busy, demo, onFile, onDemo }: { kind: 'before' | 'after'; evidence?: Evidence; active: boolean; disabled: boolean; busy: boolean; demo: boolean; onFile: (file: File) => void; onDemo: () => void }) {
  return <div className="evidence-card"><div className="evidence-label"><span>{kind === 'before' ? '01 · ANTES' : '02 · DESPUÉS'}</span>{evidence && <CheckCircle2 size={17} />}</div>{evidence ? <img src={evidence.url} alt={`Evidencia ${kind === 'before' ? 'antes' : 'después'} de la limpieza`} /> : <div className="evidence-placeholder"><Camera size={32} /><b>{kind === 'before' ? 'Así lo encontramos' : 'Así lo dejamos'}</b><p>{kind === 'before' ? 'El punto de partida de tu cambio.' : 'Deja que tu foto cuente la historia.'}</p></div>}{active && <div className="evidence-actions"><label className={`button secondary full ${disabled ? 'disabled' : ''}`}><Upload size={15} />{busy ? 'Procesando…' : evidence ? 'Cambiar foto' : 'Tomar o subir foto'}<input type="file" accept="image/jpeg,image/png,image/webp" capture="environment" aria-label={`Foto ${kind === 'before' ? 'antes' : 'después'}`} disabled={disabled} onChange={e => { const file = e.target.files?.[0]; if (file) onFile(file); e.target.value = '' }} /></label>{demo && <button className="demo-photo-button" disabled={disabled} onClick={onDemo}>Usar foto de ejemplo</button>}</div>}{evidence && <div className="evidence-meta"><span><ShieldCheck size={13} /> SHA-256 calculado</span><code title={evidence.hash}>{evidence.hash.slice(0, 18)}…</code><small>{formatDate(evidence.timestamp)} {evidence.demo && '· DEMO'}</small></div>}</div>
}
function MissionStatus({ mission }: { mission: Mission }) {
  const approved = mission.status === 'approved', rejected = mission.status === 'rejected'
  return <div className={`mission-status-banner ${mission.status}`}>{approved ? <CheckCircle2 size={34} /> : rejected ? <TriangleAlert size={34} /> : <Clock3 size={34} />}<div><h2>{approved ? '¡Una pequeña acción, un gran impacto!' : rejected ? 'Tu evidencia necesita un ajuste' : 'Tu cambio está en buenas manos'}</h2><p>{approved ? `Ganaste ${mission.points} ECO y el foco ahora está verde. Gracias por sumar.` : rejected ? mission.reason : 'La evidencia está en la cola del validador demo. Los puntos se acreditarán cuando la apruebe.'}</p></div></div>
}
