import { useState } from 'react'
import { ArrowRight, BottleWine, CheckCircle2, ChevronRight, Clock3, Coffee, Copy, Droplets, Gift, Leaf, MapPin, NotebookPen, QrCode, ShoppingBag, Sprout, Ticket, Wheat } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useEco } from './store'
import { DemoNote, Empty, Modal, PageTitle, Points, useToast } from './ui'
import { formatDate } from './data'
import type { Reward } from './types'

const icons = { Wheat, Droplets, NotebookPen, Coffee, BottleWine, Sprout }
export function RewardArt({ reward }: { reward: Reward }) {
  if (reward.image) {
    return <div className="reward-art reward-image"><img src={reward.image} alt={reward.title} /><span className="reward-art-spark">✧</span><span className="reward-art-label">BUENO PARA TI<br />BUENO PARA LIMA</span></div>
  }
  const Icon = icons[reward.icon as keyof typeof icons] ?? Gift
  return <div className="reward-art" style={{ backgroundColor: reward.color }}><span className="reward-art-circle" /><Icon strokeWidth={1.3} /><span className="reward-art-spark">✧</span><span className="reward-art-label">BUENO PARA TI<br />BUENO PARA LIMA</span></div>
}
export function Rewards() {
  const { rewards, points, vouchers } = useEco(), [tab, setTab] = useState('catálogo'), [category, setCategory] = useState('Todo')
  return <div className="standard-page"><PageTitle eyebrow="TU IMPACTO REGRESA A TI" title="Pequeñas acciones. Buenas recompensas." description="Transforma tus puntos ECO en productos y experiencias de nuestros aliados demo." /><div className="rewards-banner"><div className="rewards-banner-icon"><Gift size={37} /></div><div><span>TU BALANCE VERDE</span><div className="reward-balance">{points}<small>ECO</small><Leaf size={23} /></div><p>Cada punto cuenta una historia de cambio.</p></div><Link to="/misiones?tab=descubrir" className="button light-button">Ganar más ECO <ArrowRight size={16} /></Link><div className="banner-leaf" /></div><div className="row-between catalog-toolbar"><div className="tabs"><button className={tab === 'catálogo' ? 'active' : ''} onClick={() => setTab('catálogo')}>Catálogo</button><button className={tab === 'vouchers' ? 'active' : ''} onClick={() => setTab('vouchers')}>Mis vouchers <span>{vouchers.length}</span></button></div>{tab === 'catálogo' && <div className="pill-tabs">{['Todo', 'Alimentos', 'Experiencias', 'Accesorios'].map(c => <button key={c} className={category === c ? 'active' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div>}</div>{tab === 'catálogo' ? <div className="reward-grid">{rewards.filter(r => category === 'Todo' || r.category === category).map(reward => <Link to={`/recompensa/${reward.id}`} className="reward-card" key={reward.id}><div className="reward-image-wrap"><RewardArt reward={reward} /><span className="stock-badge">{reward.stock > 0 ? `${reward.stock} disponibles` : 'Agotado'}</span></div><div className="reward-copy"><span className="eyebrow">{reward.sponsor}</span><h3>{reward.title}</h3><p>{reward.description}</p><div className="row-between"><Points value={reward.cost} /><span className="reward-arrow"><ArrowUp /></span></div></div></Link>)}</div> : vouchers.length ? <div className="voucher-list">{vouchers.map(v => <Link key={v.id} className="surface voucher-row" to={`/voucher/${v.id}`}><span className="ticket-icon"><Ticket size={27} /></span><div><span className={`status-label ${v.usedAt ? 'approved' : 'active'}`}>{v.usedAt ? 'Utilizado' : new Date(v.expiresAt).getTime() < Date.now() ? 'Expirado' : 'Listo para canjear'}</span><h3>{v.title}</h3><span className="mono">{v.id}</span></div><ChevronRight size={20} /></Link>)}</div> : <Empty title="Algo bueno está por llegar" text="Elige una recompensa del catálogo. Aquí guardarás los vouchers de tus canjes." /> }<DemoNote>Catálogo ilustrativo. Los puntos ECO no son dinero ni se transfieren. Los aliados y productos no representan acuerdos comerciales reales.</DemoNote></div>
}
function ArrowUp() { return <ArrowRight size={19} style={{ transform: 'rotate(-35deg)' }} /> }
export function RewardDetail() {
  const { id } = useParams(), { rewards, points, redeem } = useEco(), [confirm, setConfirm] = useState(false), navigate = useNavigate(), toast = useToast()
  const reward = rewards.find(r => r.id === id)
  if (!reward) return <Empty title="Recompensa no encontrada" text="Descubre lo que tenemos para ti en el catálogo." to="/recompensas" label="Ver catálogo" />
  return <div className="standard-page"><PageTitle back eyebrow="UN REGALO POR TU IMPACTO" title={reward.title} /><div className="detail-grid reward-detail"><div><RewardArt reward={reward} /><div className="surface"><h2>Un pequeño premio, un gran significado</h2><p>{reward.description}</p><h3>Así funciona tu canje</h3><ol className="numbered-list"><li><span>1</span>Confirma el canje con tus puntos ECO.</li><li><span>2</span>Guarda el voucher QR que aparecerá en tu perfil.</li><li><span>3</span>Muéstralo en el punto de entrega dentro de 30 días.</li></ol><DemoNote>En esta demostración no se entrega ningún producto real.</DemoNote></div></div><aside className="surface"><span className="eyebrow">{reward.sponsor}</span><h2>{reward.title}</h2><div className="detail-price"><Points value={reward.cost} /></div><p className="muted">Disponibles: {reward.stock} unidades</p><div className="mission-meta"><span>Tu saldo actual</span><Points value={points} small /></div><div className="mission-meta"><span>Saldo después del canje</span><b>{Math.max(0, points - reward.cost)} ECO</b></div><div className="pickup"><MapPin size={19} /><div><b>Recoge tu recompensa</b><p>{reward.location}</p></div></div><button className="button primary full" disabled={points < reward.cost || reward.stock < 1} onClick={() => setConfirm(true)}>{reward.stock < 1 ? 'Recompensa agotada' : points < reward.cost ? `Te faltan ${reward.cost - points} ECO` : 'Canjear recompensa'}<Gift size={17} /></button>{points < reward.cost && <Link className="button text-button full" to="/">Buscar una misión</Link>}<p className="small-text muted"><Clock3 size={13} /> Voucher válido por 30 días. Un solo uso.</p></aside></div>{confirm && <Modal title="Tu impacto se convierte en recompensa" onClose={() => setConfirm(false)}><p>Canjearás <b>{reward.cost} ECO</b> por <b>{reward.title}</b>. Tu saldo quedará en {points - reward.cost} ECO.</p><DemoNote>Este canje es una simulación y se guardará en este dispositivo.</DemoNote><div className="modal-actions"><button className="button secondary" onClick={() => setConfirm(false)}>Volver</button><button className="button primary" onClick={() => { try { const voucher = redeem(reward.id); void navigate(`/voucher/${voucher}`) } catch (e) { toast((e as Error).message); setConfirm(false) } }}>Confirmar canje <CheckCircle2 size={17} /></button></div></Modal>}</div>
}
export function VoucherPage() {
  const { id } = useParams(), { vouchers, rewards, consumeVoucher } = useEco(), [confirm, setConfirm] = useState(false), toast = useToast()
  const voucher = vouchers.find(v => v.id === id), reward = rewards.find(r => r.id === voucher?.rewardId)
  if (!voucher) return <Empty title="No encontramos este voucher" text="Consulta tus recompensas para ver tus canjes." to="/recompensas" label="Ver recompensas" />
  const expired = new Date(voucher.expiresAt).getTime() < Date.now()
  return <div className="standard-page narrow-page"><PageTitle back eyebrow="EL CAMBIO TAMBIÉN SE CELEBRA" title={voucher.usedAt ? '¡Recompensa entregada en la demo!' : 'Tu recompensa está lista'} description="Gracias por hacer de Lima un lugar más verde." /><div className="voucher-ticket"><div className="voucher-ticket-head"><span className="ticket-icon"><ShoppingBag size={28} /></span><span className="eyebrow">VOUCHER ECOBONUS · DEMO</span><h2>{voucher.title}</h2><p>{reward?.sponsor}</p></div><div className="ticket-divider"><i /><span /><i /></div><div className="qr-panel">{voucher.usedAt ? <div className="voucher-used"><CheckCircle2 size={90} /><h3>Voucher utilizado</h3><p>{formatDate(voucher.usedAt)}</p></div> : expired ? <div className="voucher-used"><Clock3 size={75} /><h3>Voucher expirado</h3></div> : <><QRCodeSVG value={JSON.stringify({ type: 'ECOBONUS_DEMO', id: voucher.id, reward: voucher.rewardId, expires: voucher.expiresAt })} size={190} level="M" marginSize={2} /><span className="qr-caption">SIMULACIÓN · SIN VALOR COMERCIAL</span></>}<div className="voucher-code"><code>{voucher.id}</code><button aria-label="Copiar código del voucher" onClick={async () => { try { await navigator.clipboard.writeText(voucher.id); toast('Código copiado.') } catch { toast('No se pudo copiar. Selecciona el código para copiarlo manualmente.') } }}><Copy size={16} /></button></div><p>Vence el {formatDate(voucher.expiresAt)}</p></div><div className="voucher-footer"><MapPin size={19} /><div><b>Punto de entrega</b><p>{reward?.location}</p></div></div></div><div className="voucher-page-actions"><Link to="/recompensas" className="button secondary"><Gift size={17} /> Ver más recompensas</Link><button className="button primary" disabled={!!voucher.usedAt || expired} onClick={() => setConfirm(true)}><QrCode size={17} />{voucher.usedAt ? 'Ya utilizado' : 'Simular entrega'}</button></div><DemoNote>Este QR identifica un voucher local de demostración. La validación segura de uso único y el registro Stellar requieren el backend.</DemoNote>{confirm && <Modal title="Simular entrega del producto" onClose={() => setConfirm(false)}><p>El voucher quedará marcado como utilizado y no podrá volverse a usar en esta demo.</p><div className="modal-actions"><button className="button secondary" onClick={() => setConfirm(false)}>Volver</button><button className="button primary" onClick={() => { try { consumeVoucher(voucher.id); setConfirm(false); toast('Entrega de demostración registrada.') } catch (e) { toast((e as Error).message) } }}>Confirmar entrega</button></div></Modal>}</div>
}
